name: Import to ACR
description: "Imports a Docker Image from GitHub Container Registry to Azure Container Registry"

inputs:
  azure-cli-version:
    description: 'Version of Azure CLI to use'
    required: false
    default: 2.69.0
  azure-tenant-id:
    description: 'Azure Tenant ID'
    required: false
  azure-subscription-id:
    description: 'Azure Subscription ID'
    required: false
  azure-acr-client-id:
    description: 'Azure Container Registry Service Principal Client ID'
    required: false
  azure-acr-credentials:
    description: 'Azure Container Registry Service Principal Client Credentials in JSON'
    required: false
  azure-acr-name:
    description: 'Name of the Azure Container Registry'
    required: true
  image-name:
    description: 'Name of your Docker image'
    required: true
  tag-prefix:
    description: 'Prefix that you want to add to all of the published image tags'
    required: false
  github-token:
    description: 'The GITHUB_TOKEN'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Set outputs
      shell: bash
      id: var
      run: |
        GIT_REF=${{ github.ref_name }}
        GIT_BRANCH=${GIT_REF//\//-}
        CHECKED_OUT_SHA="$(git log -1 '--format=format:%H')"
        GITHUB_REPOSITORY=${{ github.repository }}
        echo "branch=$GIT_BRANCH" >> $GITHUB_OUTPUT
        echo "checked-out-sha=${CHECKED_OUT_SHA}" >> $GITHUB_OUTPUT
        echo "github_repository_lc=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

    - name: Login with OIDC
      if: env.AZURE_TENANT_ID && env.AZURE_SUBSCRIPTION && env.AZURE_ACR_CLIENT_ID
      uses: azure/login@v2
      with:
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}
        client-id: ${{ inputs.azure-acr-client-id }}

    - name: Login with Client Secret
      if: ${{ !(env.AZURE_TENANT_ID && env.AZURE_SUBSCRIPTION && env.AZURE_ACR_CLIENT_ID) }}
      uses: azure/login@v2
      with:
        creds: ${{ inputs.azure-acr-credentials }}

    - name: Import to ACR
      uses: azure/cli@v2
      with:
        azcliversion: ${{ inputs.azure-cli-version }}
        inlineScript: |
          TAGS=(
            ${{ inputs.tag-prefix }}${{ steps.var.outputs.branch }}
            ${{ inputs.tag-prefix }}sha-${{ steps.var.outputs.checked-out-sha }}
            ${{ inputs.tag-prefix }}latest
          )
          az config set extension.use_dynamic_install=yes_without_prompt
          echo "### Imported 📥" >> $GITHUB_STEP_SUMMARY
          for tag in "${TAGS[@]}"
          do
            az acr import \
              --name ${{ inputs.azure-acr-name }} \
              --source "ghcr.io/${{ steps.var.outputs.github_repository_lc }}:$tag" \
              --image "${{ inputs.image-name }}:$tag" \
              --username ${{ github.actor }} \
              --password ${{ inputs.github-token }} \
              --force
            echo "- ${{ inputs.azure-acr-name }}.azurecr.io/${{ inputs.image-name }}:$tag" >> $GITHUB_STEP_SUMMARY
          done
