name: Build, push, deploy

on:
  workflow_call:
    inputs:
      docker-image-name:
        description: 'The name of your Docker image'
        required: true
        type: string
      docker-build-file-name:
        description: 'The filename of a Dockerfile'
        default: 'Dockerfile'
        required: false
        type: string
      docker-build-context:
        description: 'The relative or absolute path to a local directory containing a Dockerfile'
        default: '.'
        required: false
        type: string
      docker-build-args:
        description: 'Specify additional arguments to pass to your Docker image during build time'
        required: false
        type: string
      environment:
        description: 'Specify the environment you are deploying to'
        default: 'development'
        required: false
        type: string
    secrets:
      azure-acr-credentials:
        required: true
      azure-acr-name:
        required: true
      azure-aca-credentials:
        required: true
      azure-aca-name:
        required: true
      azure-aca-resource-group:
        required: true

jobs:
  set-env:
    name: Set environment variables
    runs-on: ubuntu-22.04
    outputs:
      environment: ${{ steps.var.outputs.environment }}
      branch: ${{ steps.var.outputs.branch }}
      checked-out-sha: ${{ steps.var.outputs.checked-out-sha }}
      github_repository_lc: ${{ steps.var.outputs.github_repository_lc }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - id: var
        run: |
          GIT_REF=${{ github.ref_name }}
          GIT_BRANCH=${GIT_REF//\//-}
          INPUT_ENVIRONMENT=${{ inputs.environment }}
          ENVIRONMENT=${INPUT_ENVIRONMENT:-"development"}
          CHECKED_OUT_SHA="$(git log -1 '--format=format:%H')"
          GITHUB_REPOSITORY=${{ github.repository }}
          echo "environment=${ENVIRONMENT,,}" >> $GITHUB_OUTPUT
          echo "branch=$GIT_BRANCH" >> $GITHUB_OUTPUT
          echo "checked-out-sha=${CHECKED_OUT_SHA}" >> $GITHUB_OUTPUT
          echo "github_repository_lc=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

  build-and-push-image:
    name: Build and push to GHCR
    needs: set-env
    runs-on: ubuntu-22.04
    environment: ${{ needs.set-env.outputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: GitHub Container Registry login
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.docker-build-context }}
          file: ${{ inputs.docker-build-file-name }}
          build-args: |
            ${{ inputs.docker-build-args }}
            COMMIT_SHA=${{ needs.set-env.outputs.checked-out-sha }}
          secrets: github_token=${{ secrets.GITHUB_TOKEN }}
          tags: |
            ghcr.io/${{ needs.set-env.outputs.github_repository_lc }}:${{ needs.set-env.outputs.branch }}
            ghcr.io/${{ needs.set-env.outputs.github_repository_lc }}:sha-${{ needs.set-env.outputs.checked-out-sha }}
            ghcr.io/${{ needs.set-env.outputs.github_repository_lc }}:latest
          push: true
          cache-from: type=gha

  acr-import:
    name: Import images to ${{ needs.set-env.outputs.environment }} ACR
    needs: [ build-and-push-image, set-env ]
    runs-on: ubuntu-22.04
    environment: ${{ needs.set-env.outputs.environment }}
    steps:
      - name: Azure login with ACR credentials
        uses: azure/login@v2
        with:
          creds: ${{ secrets.azure-acr-credentials }}

      - name: Run ACR Import
        uses: azure/cli@v2
        with:
          azcliversion: 2.40.0
          inlineScript: |
            TAGS=(
              ${{ needs.set-env.outputs.branch }}
              sha-${{ needs.set-env.outputs.checked-out-sha }}
              latest
            )
            az config set extension.use_dynamic_install=yes_without_prompt
            for tag in "${TAGS[@]}"
            do
              az acr import \
                --name ${{ secrets.azure-acr-name }} \
                --source "ghcr.io/${{ needs.set-env.outputs.github_repository_lc }}:$tag" \
                --image "${{ inputs.docker-image-name }}:$tag" \
                --username ${{ github.actor }} \
                --password ${{ secrets.GITHUB_TOKEN }} \
                --force
            done

  deploy-image:
    name: Deploy '${{ needs.set-env.outputs.branch }}' to ${{ needs.set-env.outputs.environment }}
    needs: [ build-and-push-image, set-env ]
    runs-on: ubuntu-22.04
    environment: ${{ needs.set-env.outputs.environment }}
    steps:
      - name: Azure login with ACA credentials
        uses: azure/login@v2
        with:
          creds: ${{ secrets.azure-aca-credentials }}

      - name: Update Azure Container Apps Revision
        uses: azure/CLI@v2
        id: azure
        with:
          azcliversion: 2.53.1
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp update \
              --name ${{ secrets.azure-aca-name }} \
              --resource-group ${{ secrets.azure-aca-resource-group }} \
              --image ${{ secrets.azure-acr-name }}.azurecr.io/${{ inputs.docker-image-name }}:sha-${{ needs.set-env.outputs.checked-out-sha }} \
              --output none
