name: Build, push, deploy

on:
  workflow_call:
    inputs:
      docker-image-name:
        description: 'Name of your Docker image'
        required: true
        type: string
      docker-build-file-name:
        description: 'Filename of a Dockerfile'
        default: 'Dockerfile'
        required: false
        type: string
      docker-build-context:
        description: 'Relative or absolute path to a local directory containing a Dockerfile'
        default: '.'
        required: false
        type: string
      docker-build-args:
        description: 'Additional arguments to pass to your Docker image during build time'
        required: false
        type: string
      docker-build-target:
        description: 'Target layer in the Dockerfile you want to build'
        required: false
        type: string
      docker-tag-prefix:
        description: 'Prefix that you want to add to all of the published image tags'
        required: false
        type: string
      import-without-deploy:
        description: 'Import the image but do not deploy it?'
        required: false
        default: false
        type: boolean
      environment:
        description: 'Environment you are deploying to'
        default: 'development'
        required: false
        type: string
      annotate-release:
        description: 'Annotate the release in App Insights?'
        default: false
        required: false
        type: boolean
    secrets:
      azure-tenant-id:
        required: false
      azure-subscription-id:
        required: false
      azure-aca-client-id:
        required: false
      azure-aca-credentials:
        required: false
      azure-aca-name:
        required: true
      azure-aca-resource-group:
        required: true
      azure-acr-client-id:
        required: false
      azure-acr-credentials:
        required: false
      azure-acr-name:
        required: true

env:
  AZURE_CLI_VERSION: 2.68.0

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      environment: ${{ inputs.environment }}
      docker-image-name: ${{ inputs.docker-image-name }}
      docker-build-file-name: ${{ inputs.docker-build-file-name }}
      docker-build-context: ${{ inputs.docker-build-context }}
      docker-build-args: ${{ inputs.docker-build-args }}
      docker-build-target: ${{ inputs.docker-build-target }}
      docker-tag-prefix: ${{ inputs.docker-tag-prefix }}
    secrets: inherit

  import:
    needs: [ build ]
    uses: ./.github/workflows/import.yml
    with:
      environment: ${{ inputs.environment }}
      az-cli-version: ${{ env.AZURE_CLI_VERSION }}
      docker-image-name: ${{ inputs.docker-image-name }}
      docker-tag-prefix: ${{ inputs.docker-tag-prefix }}
    secrets: inherit

  deploy:
    needs: [ import ]
    uses: ./.github/workflows/deploy.yml
    if: ${{ inputs.import-without-deploy == false }}
    with:
      environment: ${{ inputs.environment }}
      az-cli-version: ${{ env.AZURE_CLI_VERSION }}
      docker-image-name: ${{ inputs.docker-image-name }}
      docker-tag-prefix: ${{ inputs.docker-tag-prefix }}
    secrets: inherit
