name: Build, import, deploy

on:
  workflow_call:
    inputs:
      docker-image-name:
        description: 'Name of your Docker image'
        required: true
        type: string
      docker-build-file-name:
        description: 'Filename of a Dockerfile'
        default: 'Dockerfile'
        required: false
        type: string
      docker-build-context:
        description: 'Relative or absolute path to a local directory containing a Dockerfile'
        default: '.'
        required: false
        type: string
      docker-build-args:
        description: 'Additional arguments to pass to your Docker image during build time'
        required: false
        type: string
      docker-build-target:
        description: 'Target layer in the Dockerfile you want to build'
        required: false
        type: string
      docker-tag-prefix:
        description: 'Prefix that you want to add to all of the published image tags'
        required: false
        type: string
      import-without-deploy:
        description: 'Import the image but do not deploy it?'
        required: false
        default: false
        type: boolean
      annotate-release:
        description: 'Annotate the release in App Insights?'
        default: false
        required: false
        type: boolean
      app-insights-name:
        description: 'Name of App Insights resource'
        required: false
        type: string
      environment:
        description: 'Environment you are deploying to'
        default: 'development'
        required: false
        type: string

    secrets:
      azure-tenant-id:
        required: false
      azure-subscription-id:
        required: false
      azure-aca-client-id:
        required: false
      azure-aca-credentials:
        required: false
      azure-aca-name:
        required: true
      azure-aca-resource-group:
        required: true
      azure-acr-client-id:
        required: false
      azure-acr-credentials:
        required: false
      azure-acr-name:
        required: true

env:
  AZURE_CLI_VERSION: 2.68.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - shell: bash
        run: |
          echo '## Deploying to `${{ inputs.environment }}` 🚢' >> $GITHUB_STEP_SUMMARY

      - uses: ./.github/actions/build
        with:
          build-file-name: ${{ inputs.docker-build-file-name }}
          build-context: ${{ inputs.docker-build-context }}
          build-args: ${{ inputs.docker-build-args }}
          build-target: ${{ inputs.docker-build-target }}
          image-name: ${{ inputs.docker-image-name }}
          tag-prefix: ${{ inputs.docker-tag-prefix }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/import
        with:
          azure-cli-version: ${{ env.AZURE_CLI_VERSION }}
          azure-tenant-id: ${{ secrets.azure-tenant-id }}
          azure-subscription-id: ${{ secrets.azure-subscription-id }}
          azure-acr-client-id: ${{ secrets.azure-acr-client-id }}
          azure-acr-credentials: ${{ secrets.azure-acr-credentials }}
          azure-acr-name: ${{ secrets.azure-acr-name }}
          image-name: ${{ inputs.docker-image-name }}
          tag-prefix: ${{ inputs.docker-tag-prefix }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          AZURE_TENANT_ID: ${{ secrets.azure-tenant-id || '' }}
          AZURE_SUBSCRIPTION: ${{ secrets.azure-subscription-id || '' }}
          AZURE_ACR_CLIENT_ID: ${{ secrets.azure-acr-client-id || '' }}

      - uses: ./.github/actions/deploy
        if: ${{ inputs.import-without-deploy == false }}
        with:
          azure-cli-version: ${{ env.AZURE_CLI_VERSION }}
          azure-tenant-id: ${{ secrets.azure-tenant-id }}
          azure-subscription-id: ${{ secrets.azure-subscription-id }}
          azure-aca-client-id: ${{ secrets.azure-aca-client-id }}
          azure-aca-credentials: ${{ secrets.azure-aca-credentials }}
          azure-aca-name: ${{ secrets.azure-aca-name }}
          azure-aca-resource-group: ${{ secrets.azure-aca-resource-group }}
          azure-acr-name: ${{ secrets.azure-acr-name }}
          annotate-release: ${{ inputs.annotate-release }}
          app-insights-name: ${{ inputs.app-insights-name }}
          image-name: ${{ inputs.docker-image-name }}
          tag-prefix: ${{ inputs.docker-tag-prefix }}
        env:
          AZURE_TENANT_ID: ${{ secrets.azure-tenant-id || '' }}
          AZURE_SUBSCRIPTION: ${{ secrets.azure-subscription-id || '' }}
          AZURE_ACA_CLIENT_ID: ${{ secrets.azure-aca-client-id || '' }}
