name: Build Docker image

on:
  workflow_call:
    inputs:
      docker-image-name:
        description: 'Name of your Docker image'
        required: true
        type: string
      docker-build-file-name:
        description: 'Filename of a Dockerfile'
        default: 'Dockerfile'
        required: false
        type: string
      docker-build-context:
        description: 'Relative or absolute path to a local directory containing a Dockerfile'
        default: '.'
        required: false
        type: string
      docker-build-args:
        description: 'Additional arguments to pass to your Docker image during build time'
        required: false
        type: string
      docker-build-target:
        description: 'Target layer in the Dockerfile you want to build'
        required: false
        type: string
      docker-tag-prefix:
        description: 'Prefix that you want to add to all of the published image tags'
        required: false
        type: string
      environment:
        description: 'Environment you are deploying to'
        default: 'development'
        required: false
        type: string

jobs:
  build:
    name: Build
    uses: ./.github/workflows/_build.yml
    with:
      environment: ${{ inputs.environment }}
      docker-image-name: ${{ inputs.docker-image-name }}
      docker-build-file-name: ${{ inputs.docker-build-file-name }}
      docker-build-context: ${{ inputs.docker-build-context }}
      docker-build-args: ${{ inputs.docker-build-args }}
      docker-build-target: ${{ inputs.docker-build-target }}
      docker-tag-prefix: ${{ inputs.docker-tag-prefix }}
