name: Deploy Container App

on:
  workflow_call:
    inputs:
      docker-image-name:
        description: 'Name of your Docker image'
        required: true
        type: string
      docker-tag-prefix:
        description: 'Prefix that you want to add to all of the published image tags'
        required: false
        type: string
      annotate-release:
        description: 'Annotate the release in App Insights?'
        default: false
        required: false
        type: boolean
      app-insights-name:
        description: 'Name of App Insights resource'
        required: false
        type: string
      environment:
        description: 'Environment you are deploying to'
        default: 'development'
        required: false
        type: string

    secrets:
      azure-tenant-id:
        required: false
      azure-subscription-id:
        required: false
      azure-aca-client-id:
        required: false
      azure-aca-credentials:
        required: false
      azure-aca-name:
        required: true
      azure-aca-resource-group:
        required: true
      azure-acr-name:
        required: true

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: ${{ inputs.environment }}
      docker-image-name: ${{ inputs.docker-image-name }}
      docker-tag-prefix: ${{ inputs.docker-tag-prefix }}
      annotate-release: ${{ inputs.annotate-release }}
      app-insights-name: ${{ inputs.app-insights-name}}
    secrets: inherit
