name: Deploy Container App

on:
  workflow_call:
    inputs:
      docker-image-name:
        description: 'Name of your Docker image'
        required: true
        type: string
      docker-tag-prefix:
        description: 'Prefix that you want to add to all of the published image tags'
        required: false
        type: string
      annotate-release:
        description: 'Annotate the release in App Insights?'
        default: false
        required: false
        type: boolean
      app-insights-name:
        description: 'Name of App Insights resource'
        required: false
        type: string
      environment:
        description: 'Environment you are deploying to'
        default: 'development'
        required: false
        type: string

    secrets:
      azure-tenant-id:
        required: false
      azure-subscription-id:
        required: false
      azure-aca-client-id:
        required: false
      azure-aca-credentials:
        required: false
      azure-aca-name:
        required: true
      azure-aca-resource-group:
        required: true
      azure-acr-name:
        required: true

env:
  AZURE_CLI_VERSION: 2.68.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - uses: ./.github/actions/deploy
        with:
          azure-cli-version: ${{ env.AZURE_CLI_VERSION }}
          azure-tenant-id: ${{ secrets.azure-tenant-id }}
          azure-subscription-id: ${{ secrets.azure-subscription-id }}
          azure-aca-client-id: ${{ secrets.azure-aca-client-id }}
          azure-aca-credentials: ${{ secrets.azure-aca-credentials }}
          azure-aca-name: ${{ secrets.azure-aca-name }}
          azure-aca-resource-group: ${{ secrets.azure-aca-resource-group }}
          azure-acr-name: ${{ secrets.azure-acr-name }}
          annotate-release: ${{ inputs.annotate-release }}
          app-insights-name: ${{ inputs.app-insights-name }}
          image-name: ${{ inputs.docker-image-name }}
          tag-prefix: ${{ inputs.docker-tag-prefix }}
        env:
          AZURE_TENANT_ID: ${{ secrets.azure-tenant-id || '' }}
          AZURE_SUBSCRIPTION: ${{ secrets.azure-subscription-id || '' }}
          AZURE_ACA_CLIENT_ID: ${{ secrets.azure-aca-client-id || '' }}
