name: Import to ACR

on:
  workflow_call:
    inputs:
      docker-image-name:
        description: 'Name of your Docker image'
        required: true
        type: string
      docker-tag-prefix:
        description: 'Prefix that you want to add to all of the published image tags'
        required: false
        type: string
      environment:
        description: 'Environment you are deploying to'
        default: 'development'
        required: false
        type: string

    secrets:
      azure-tenant-id:
        required: false
      azure-subscription-id:
        required: false
      azure-acr-client-id:
        required: false
      azure-acr-credentials:
        required: false
      azure-acr-name:
        required: true

jobs:
  import:
    name: Import
    uses: ./.github/workflows/_import.yml
    with:
      environment: ${{ inputs.environment }}
      docker-image-name: ${{ inputs.docker-image-name }}
      docker-tag-prefix: ${{ inputs.docker-tag-prefix }}
    secrets: inherit
