name: Import to ACR

on:
  workflow_call:
    inputs:
      docker-image-name:
        description: 'Name of your Docker image'
        required: true
        type: string
      docker-tag-prefix:
        description: 'Specify a prefix that you want to add to all of the published image tags'
        required: false
        type: string
      environment:
        description: 'Specify the environment you are deploying to'
        default: 'development'
        required: false
        type: string

    secrets:
      azure-tenant-id:
        required: false
      azure-subscription-id:
        required: false
      azure-acr-client-id:
        required: false
      azure-acr-credentials:
        required: false
      azure-acr-name:
        required: true

env:
  AZURE_CLI_VERSION: 2.68.0

jobs:
  set-env:
    name: Set environment variables
    runs-on: ubuntu-24.04
    outputs:
      branch: ${{ steps.var.outputs.branch }}
      checked-out-sha: ${{ steps.var.outputs.checked-out-sha }}
      github_repository_lc: ${{ steps.var.outputs.github_repository_lc }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - id: var
        run: |
          GIT_REF=${{ github.ref_name }}
          GIT_BRANCH=${GIT_REF//\//-}
          CHECKED_OUT_SHA="$(git log -1 '--format=format:%H')"
          GITHUB_REPOSITORY=${{ github.repository }}
          echo "branch=$GIT_BRANCH" >> $GITHUB_OUTPUT
          echo "checked-out-sha=${CHECKED_OUT_SHA}" >> $GITHUB_OUTPUT
          echo "github_repository_lc=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

  import:
    needs: [ set-env ]
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Login with OIDC
        env:
          AZURE_TENANT_ID: ${{ secrets.azure-tenant-id || '' }}
          AZURE_SUBSCRIPTION: ${{ secrets.azure-subscription-id || '' }}
          AZURE_ACR_CLIENT_ID: ${{ secrets.azure-acr-client-id || '' }}
        if: env.AZURE_TENANT_ID && env.AZURE_SUBSCRIPTION && env.AZURE_ACR_CLIENT_ID
        uses: azure/login@v2
        with:
          tenant-id: ${{ secrets.azure-tenant-id }}
          subscription-id: ${{ secrets.azure-subscription-id }}
          client-id: ${{ secrets.azure-acr-client-id }}

      - name: Login with Client Secret
        env:
          AZURE_TENANT_ID: ${{ secrets.azure-tenant-id || '' }}
          AZURE_SUBSCRIPTION: ${{ secrets.azure-subscription-id || '' }}
          AZURE_ACR_CLIENT_ID: ${{ secrets.azure-acr-client-id || '' }}
        if: ${{ !(env.AZURE_TENANT_ID && env.AZURE_SUBSCRIPTION && env.AZURE_ACR_CLIENT_ID) }}
        uses: azure/login@v2
        with:
          creds: ${{ secrets.azure-acr-credentials }}

      - name: Import to ACR
        uses: azure/cli@v2
        with:
          azcliversion: ${{ env.AZURE_CLI_VERSION }}
          inlineScript: |
            TAGS=(
              ${{ inputs.docker-tag-prefix }}${{ needs.set-env.outputs.branch }}
              ${{ inputs.docker-tag-prefix }}sha-${{ needs.set-env.outputs.checked-out-sha }}
              ${{ inputs.docker-tag-prefix }}latest
            )
            az config set extension.use_dynamic_install=yes_without_prompt
            for tag in "${TAGS[@]}"
            do
              az acr import \
                --name ${{ secrets.azure-acr-name }} \
                --source "ghcr.io/${{ needs.set-env.outputs.github_repository_lc }}:$tag" \
                --image "${{ inputs.docker-image-name }}:$tag" \
                --username ${{ github.actor }} \
                --password ${{ secrets.GITHUB_TOKEN }} \
                --force
            done
