name: Import to ACR

on:
  workflow_call:
    inputs:
      docker-image-name:
        description: 'Name of your Docker image'
        required: true
        type: string
      docker-tag-prefix:
        description: 'Prefix that you want to add to all of the published image tags'
        required: false
        type: string
      environment:
        description: 'Environment you are deploying to'
        default: 'development'
        required: false
        type: string

    secrets:
      azure-tenant-id:
        required: false
      azure-subscription-id:
        required: false
      azure-acr-client-id:
        required: false
      azure-acr-credentials:
        required: false
      azure-acr-name:
        required: true

jobs:
  import:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: ./.github/actions/import
        with:
          azure-cli-version: ${{ env.AZURE_CLI_VERSION }}
          azure-tenant-id: ${{ secrets.azure-tenant-id }}
          azure-subscription-id: ${{ secrets.azure-subscription-id }}
          azure-acr-client-id: ${{ secrets.azure-acr-client-id }}
          azure-acr-credentials: ${{ secrets.azure-acr-credentials }}
          azure-acr-name: ${{ secrets.azure-acr-name }}
          image-name: ${{ inputs.docker-image-name }}
          tag-prefix: ${{ inputs.docker-tag-prefix }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          AZURE_TENANT_ID: ${{ secrets.azure-tenant-id || '' }}
          AZURE_SUBSCRIPTION: ${{ secrets.azure-subscription-id || '' }}
          AZURE_ACR_CLIENT_ID: ${{ secrets.azure-acr-client-id || '' }}
